### ISSUE TITLE
SoapySDR 0.8.2/0.9.0 checklist

### ISSUE THREAD

**Issue by ncorgan** [pothosware/SoapySDR#405]
0.8.2
- [ ] https://github.com/pothosware/SoapySDR/pull/404 (Solves OS X Monterey bug)
- [ ] https://github.com/pothosware/SoapySDR/issues/399

0.9.0
- [ ] Prepare docs site for https://github.com/pothosware/SoapySDR/issues/403

**Comment by metasim** [comment]
Curious to know if this work still ongoing? There's a feature in the SoapyBladeRF module we'd like to use that was merged June 2022, but it seems like 0.8.1 was July 2021(?).

**Comment by numinit** [comment]
We're starting to package master in nixpkgs for Python 3.12 compatibility.
